### ISSUE TITLE
weasyprint layer - Cannot load library 'libpango-1.0-0'

### ISSUE THREAD

**Issue by ArmandoSep** [kotify/cloud-print-utils#35]
Hello, I'm newer in python. I followed the steps to deploy the weasyprint layer but I get this error while importing the package into Lambda. Do you know how to fix it?

Cannot load library 'libpango-1.0-0': libpango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libpango-1.0-0'",

Thanks!

**Comment by lvenki94** [comment]
Hi @ArmandoSep 

I followed the instructions carefully and had the same issue, since you marked this completed, can you help me with how you were able to fix it?

Adding a link to the zip: https://drive.google.com/file/d/1ofzYSsH76zjiePlMmvevQOvBKUuYbWgy/view?usp=sharing
I have added the ENV vars as mentioned in the Readme.md and the runtime architecture is x86-64.
Lambda Runtime is python3.12

```{
  "errorMessage": "cannot load library 'libpango-1.0-0': libpango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libpango-1.0-0'",
  "errorType": "OSError",
  "requestId": "",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.12/importlib/__init__.py\", line 90, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n",
    "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n",
    "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n",
    "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n",
    "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n",
    "  File \"/var/task/lambda_function.py\", line 2, in <module>\n    from weasyprint import HTML, CSS\n",
    "  File \"/opt/python/lib/python3.12/site-packages/weasyprint/__init__.py\", line 425, in <module>\n    from .css import preprocess_stylesheet  # noqa: I001, E402\n",
    "  File \"/opt/python/lib/python3.12/site-packages/weasyprint/css/__init__.py\", line 28, in <module>\n    from .computed_values import COMPUTER_FUNCTIONS\n",
    "  File \"/opt/python/lib/python3.12/site-packages/weasyprint/css/computed_values.py\", line 9, in <module>\n    from ..text.ffi import FROM_UNITS, ffi, pango\n",
    "  File \"/opt/python/lib/python3.12/site-packages/weasyprint/text/ffi.py\", line 450, in <module>\n    pango = _dlopen(\n",
    "  File \"/opt/python/lib/python3.12/site-packages/weasyprint/text/ffi.py\", line 435, in _dlopen\n    return ffi.dlopen(names[0], flags)  # pragma: no cover\n",
    "  File \"/opt/python/lib/python3.12/site-packages/cffi/api.py\", line 150, in dlopen\n    lib, function_cache = _make_ffi_library(self, name, flags)\n",
    "  File \"/opt/python/lib/python3.12/site-packages/cffi/api.py\", line 834, in _make_ffi_library\n    backendlib = _load_backend_lib(backend, libname, flags)\n",
    "  File \"/opt/python/lib/python3.12/site-packages/cffi/api.py\", line 829, in _load_backend_lib\n    raise OSError(msg)\n"
  ]
}

Function Logs:
-----
WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting 
-----
[ERROR] OSError: cannot load library 'libpango-1.0-0': libpango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libpango-1.0-0'
Traceback (most recent call last):
  File "/var/lang/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 2, in <module>
    from weasyprint import HTML, CSS
  File "/opt/python/lib/python3.12/site-packages/weasyprint/__init__.py", line 425, in <module>
    from .css import preprocess_stylesheet  # noqa: I001, E402
  File "/opt/python/lib/python3.12/site-packages/weasyprint/css/__init__.py", line 28, in <module>
    from .computed_values import COMPUTER_FUNCTIONS
  File "/opt/python/lib/python3.12/site-packages/weasyprint/css/computed_values.py", line 9, in <module>
    from ..text.ffi import FROM_UNITS, ffi, pango
  File "/opt/python/lib/python3.12/site-packages/weasyprint/text/ffi.py", line 450, in <module>
    pango = _dlopen(
  File "/opt/python/lib/python3.12/site-packages/weasyprint/text/ffi.py", line 435, in _dlopen
    return ffi.dlopen(names[0], flags)  # pragma: no cover
  File "/opt/python/lib/python3.12/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/opt/python/lib/python3.12/site-packages/cffi/api.py", line 834, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/opt/python/lib/python3.12/site-packages/cffi/api.py", line 829, in _load_backend_lib
    raise OSError(msg)
INIT_REPORT Init Duration: 1217.44 ms	Phase: invoke	Status: error	Error Type: Runtime.Unknown
START RequestId: af7fb275-0817-4d54-9324-d214ce354ea0 Version: $LATEST
END RequestId: af7fb275-0817-4d54-9324-d214ce354ea0
REPORT RequestId: af7fb275-0817-4d54-9324-d214ce354ea0	Duration: 1226.89 ms	Billed Duration: 1227 ms	Memory Size: 512 MB	Max Memory Used: 63 MB	Status: error	Error Type: Runtime.Unknown

Request ID: af7fb275-0817-4d54-9324-d214ce354ea0```

Above is the stack trace of the issue. 
Please let me know how I can resolve this.

Regards
Venkatesh L

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/0d4c1940-3b3a-4bd0-9a8f-b2f02040f23a" />

**Comment by ArmandoSep** [comment]
Hello @lvenki94! The error for me was in the ENV variables. 

<img width="1160" alt="Image" src="https://github.com/user-attachments/assets/e15f8838-3ac9-4ebc-8489-ddd5de6b131c" />

Feel free to try my layer, it works for python 3.12. I´m using it in N. Virginia. 
https://drive.google.com/file/d/1Jj39AfTA7SQkwvO6IneE4flmmWKAZj81/view?usp=sharing

**Comment by lvenki94** [comment]
Got it Thank you. It is working for me when using the release zip, but not when I build the zip myself with the given instructions. 
Thanks for the help. Much appreciated.

Regards
Venkatesh L

**Comment by samuelmesq** [comment]
Hi, I know this issue is closed, but I’d like to share what I found in case it helps others.

I encountered the same issue, and after some debugging, I was able to reproduce it with just a few lines:

```python
import ctypes

ctypes.CDLL("libpango-1.0.so.0")
```

This changed the error to:

```
/opt/lib/libpango-1.0.so.0: undefined symbol: g_once_init_leave_pointer
```

I then added `libglib-2.0.so.0` before libpango, which reverted the error back to the previous one: `cannot load library 'libpango-1.0-0'`


Eventually, I was able to resolve the issue by loading the full library paths explicitly:

```diff
+ctypes.CDLL("/opt/lib/libglib-2.0.so.0")
+ctypes.CDLL("/opt/lib/libpango-1.0.so.0")
```

After further tweaking and testing, I returned to my original code, and now it's working by simply adding this line at the top of my Lambda handler:

```python
import ctypes
ctypes.CDLL("/opt/lib/libglib-2.0.so.0")
```

For context:  
- **Python version:** 3.13  
- **WeasyPrint version:** v65

Hope this helps someone else running into the same issue!

**Comment by kalekseev** [comment]
@samuelmesq do you have LD_LIBRARY_PATH="/opt/lib" in your lambda env as instructed by the readme?

**Comment by samuelmesq** [comment]
Hi @kalekseev 

I never set it initially because of what’s stated in the AWS docs:  
https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime

Under **Unreserved environment variables**, it mentions that `LD_LIBRARY_PATH` is already set to include:

```
/var/lang/lib:/lib64:/usr/lib64:$LAMBDA_RUNTIME_DIR:$LAMBDA_RUNTIME_DIR/lib:$LAMBDA_TASK_ROOT:$LAMBDA_TASK_ROOT/lib:/opt/lib
```

So I assumed that since `/opt/lib` was already listed, it would be valid by default, and I didn’t try explicitly setting it to just `/opt/lib`.

I even added `WEASYPRINT_DLL_DIRECTORIES`, hoping it would have some effect.

But in conclusion—you’re absolutely right: **explicitly setting `LD_LIBRARY_PATH` to `/opt/lib` solved the issue.**

Thank you for reply.
